spring.application.name=p2

server.port=8081

spring.datasource.url=jdbc:h2:file:./testdb
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.p2.generate-ddl=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.p2.defer-datasource-initialization=true

